version: '3'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always

    ports:
      - "8080:80"
    networks:
      - app-network
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
      image: postgres:latest
      
      env_file:
      - .env

      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_HOST: ${POSTGRES_HOST}

      networks:
        - app-network
      volumes:
        - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 
networks:
  app-network:




